repos:
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: master
    hooks:
      - id: go-mod-tidy-repo
      - id: go-fmt-repo
      - id: go-test-repo-mod
      - id: go-imports-repo
      - id: golangci-lint-repo-mod
      - id: my-cmd-repo-mod
        name: go-test-mod
        alias: go-test-mod
        args: [ go, test, -coverprofile=coverage.out,  ./... ]